name: Windows-RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Enable RDP
        shell: powershell
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      ## name: Create User
      ##  shell: powershell
       ## run: |
         ## net user runneradmin P@ssw0rd123 /add
       ##   net localgroup administrators runneradmin /add
      - name: Create User
        shell: powershell
        run: |
          cmd /c "net user runneradmin P@ssw0rd123 /add || exit /b 0"
          cmd /c "net localgroup administrators runneradmin /add || exit /b 0"
      #- name: Download LocalXpose
       # shell: powershell
       # run: |
         # Invoke-WebRequest https://localxpose.io/api/v2/downloads/loclx-windows-amd64.zip -OutFile loclx.zip
        #  Expand-Archive loclx.zip
     # - name: Download LocalXpose
      #  shell: powershell
      #  run: |
       #   Invoke-WebRequest https://github.com/localxpose/localxpose/releases/download/v1.4.0/loclx-windows-amd64.exe -OutFile loclx.exe
          
      #  shell: powershell
        #run: |
          #curl.exe -L "https://github.com/localxpose/localxpose/releases/download/v1.4.0/loclx-windows-amd64.exe" -o loclx.exe
     
           - name: Download LocalXpose
        shell: powershell
        run: |
          curl.exe -L "https://github.com/localxpose/localxpose/releases/download/v1.4.0/loclx-windows-amd64.exe" -o loclx.exe
     
      - name: Login LocalXpose
        shell: powershell
        run: |
          .\loclx.exe auth EUfoSVK9cRcpxhPMv1nt9FyqbO1ip3dyGzleB3YM

      - name: Create Tunnel
        shell: powershell
        run: |
          Start-Process .\loclx.exe -ArgumentList "tunnel tcp --to 3389"

      - name: Show Tunnel
        shell: powershell
        run: |
          Start-Sleep -Seconds 20
          Get-Content "$env:USERPROFILE\.loclx\loclx.log"

      - name: Keep Alive
        shell: powershell
        run: |
          while ($true) {
            Start-Sleep -Seconds 60
          }